"""added code to lab order model

Revision ID: 0e7f9f17faea
Revises: f98fc1567fbe
Create Date: 2024-10-29 03:33:53.795352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7f9f17faea'
down_revision = 'f98fc1567fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
