"""added assoc tables

Revision ID: 0f9f3bd44fe0
Revises: c6bb243f11bd
Create Date: 2024-11-27 15:55:44.748263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9f3bd44fe0'
down_revision = 'c6bb243f11bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_customer_drug_allergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_customer_underlying_diseases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_disease_assoc',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['lab_customers.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['lab_customer_underlying_diseases.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('customer_drug_assoc',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['lab_customers.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['lab_customer_drug_allergies.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_drug_assoc')
    op.drop_table('customer_disease_assoc')
    op.drop_table('lab_customer_underlying_diseases')
    op.drop_table('lab_customer_drug_allergies')
    # ### end Alembic commands ###
