"""added lab ID field

Revision ID: 1d431a6fbc4e
Revises: 0f9f3bd44fe0
Create Date: 2024-11-27 16:05:54.029543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d431a6fbc4e'
down_revision = '0f9f3bd44fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_customer_drug_allergies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'labs', ['lab_id'], ['id'])

    with op.batch_alter_table('lab_customer_underlying_diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'labs', ['lab_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_customer_underlying_diseases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lab_id')

    with op.batch_alter_table('lab_customer_drug_allergies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lab_id')

    # ### end Alembic commands ###
