"""added receipt id field

Revision ID: 2c20bd7ea99d
Revises: d3e30d892831
Create Date: 2024-12-03 08:30:06.023428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c20bd7ea99d'
down_revision = 'd3e30d892831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_disease_assoc', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customer_drug_assoc', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_id', sa.String(), nullable=True))

    with op.batch_alter_table('test_profile_assoc', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_profile_assoc', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.drop_column('receipt_id')

    with op.batch_alter_table('customer_drug_assoc', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('customer_disease_assoc', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
