"""added medication for customers

Revision ID: 37f6a6eafcd6
Revises: 91d31213fbe0
Create Date: 2024-11-29 11:47:01.051740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f6a6eafcd6'
down_revision = '91d31213fbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_customer_medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_medication_assoc',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['lab_customers.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['lab_customer_medications.id'], )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_medication_assoc')
    op.drop_table('lab_customer_medications')
    # ### end Alembic commands ###
