"""added the lab test profile assoc table

Revision ID: 3cf6fce39817
Revises: 082deb72c570
Create Date: 2024-11-14 07:31:43.589147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf6fce39817'
down_revision = '082deb72c570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_test_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_profile_assoc_version',
    sa.Column('test_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('test_id', 'transaction_id')
    )
    with op.batch_alter_table('test_profile_assoc_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_profile_assoc_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_profile_assoc_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_profile_assoc_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('test_profile_assoc',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['lab_test_profiles.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_profile_assoc')
    with op.batch_alter_table('test_profile_assoc_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_profile_assoc_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_test_profile_assoc_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_test_profile_assoc_version_end_transaction_id'))

    op.drop_table('test_profile_assoc_version')
    op.drop_table('lab_test_profiles')
    # ### end Alembic commands ###
