"""added max volume

Revision ID: 451610ee6395
Revises: e9eca97ab125
Create Date: 2024-10-29 02:24:13.852991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451610ee6395'
down_revision = 'e9eca97ab125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_specimen_containers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_volume', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_specimen_containers', schema=None) as batch_op:
        batch_op.drop_column('max_volume')

    # ### end Alembic commands ###
