"""add field payment_remarks

Revision ID: 687495572bbf
Revises: 75683cf127bb
Create Date: 2025-03-14 16:16:02.819503
add to origin
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687495572bbf'
down_revision = '75683cf127bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_remarks', sa.Text(), nullable=True))

    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('lab_test_orders', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_orders', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.drop_column('payment_remarks')

    # ### end Alembic commands ###
