"""added Lab package model

Revision ID: 7329ba6541d7
Revises: eb1039a8a5cf
Create Date: 2025-02-04 14:19:21.318897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7329ba6541d7'
down_revision = 'eb1039a8a5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_service_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_service_packages')
    # ### end Alembic commands ###
