"""added latitude and longitude

Revision ID: 737ffc9f57b8
Revises: 37f6a6eafcd6
Create Date: 2024-12-02 10:43:55.368794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737ffc9f57b8'
down_revision = '37f6a6eafcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('long', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_column('long')
        batch_op.drop_column('lat')
    # ### end Alembic commands ###
