"""added emergency fields

Revision ID: 91d31213fbe0
Revises: f3e82fbc8e87
Create Date: 2024-11-29 11:39:34.966535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d31213fbe0'
down_revision = 'f3e82fbc8e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_telephone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_customers', schema=None) as batch_op:
        batch_op.drop_column('emergency_telephone')
        batch_op.drop_column('emergency_person')

    # ### end Alembic commands ###
