"""add any field for discount process

Revision ID: 92a371dd5d43
Revises: 687495572bbf
Create Date: 2025-04-21 12:08:08.347813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a371dd5d43'
down_revision = '687495572bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grand_total_amount', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.drop_column('grand_total_amount')
        batch_op.drop_column('discount_type')

    # ### end Alembic commands ###
