"""added update datetime field

Revision ID: 99ca8abeb8cd
Revises: 9f2de5e01fe3
Create Date: 2025-02-06 10:03:56.324459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ca8abeb8cd'
down_revision = '9f2de5e01fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
