"""added TAT field

Revision ID: 9a1b4a038ea7
Revises: c0bc0a08bca1
Create Date: 2024-12-13 15:05:01.127470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1b4a038ea7'
down_revision = 'c0bc0a08bca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tat', sa.String(), nullable=True))

    with op.batch_alter_table('lab_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tat', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests_version', schema=None) as batch_op:
        batch_op.drop_column('tat')

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_column('tat')

    # ### end Alembic commands ###
