"""added profile active field

Revision ID: 9e179cc388ab
Revises: 9a1b4a038ea7
Create Date: 2025-01-29 08:35:23.317049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e179cc388ab'
down_revision = '9a1b4a038ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
