"""added lab ID field

Revision ID: 9f2de5e01fe3
Revises: b5bd4d2d1b89
Create Date: 2025-02-04 14:36:11.476041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2de5e01fe3'
down_revision = 'b5bd4d2d1b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'labs', ['lab_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lab_id')

    # ### end Alembic commands ###
