"""added unique constraint to the code field

Revision ID: b3f4016da056
Revises: e8f34298afb6
Create Date: 2025-02-24 10:59:04.585645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f4016da056'
down_revision = 'e8f34298afb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_lab_service_packages_code', ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.drop_constraint('unique_lab_service_packages_code', type_='unique')

    # ### end Alembic commands ###
