"""added assoc tables for tests, test profiles and packages

Revision ID: b5bd4d2d1b89
Revises: 7329ba6541d7
Create Date: 2025-02-04 14:22:55.140401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bd4d2d1b89'
down_revision = '7329ba6541d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_test_profile_package_assoc',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['lab_service_packages.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['lab_test_profiles.id'], )
    )
    op.create_table('lab_test_package_assoc',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['lab_service_packages.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_test_package_assoc')
    op.drop_table('lab_test_profile_package_assoc')
    # ### end Alembic commands ###
