"""added lab ID field to the models

Revision ID: b79bdb16c8ee
Revises: 451610ee6395
Create Date: 2024-10-29 02:41:30.776807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79bdb16c8ee'
down_revision = '451610ee6395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_specimen_container_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'labs', ['lab_id'], ['id'])

    with op.batch_alter_table('lab_specimen_containers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'labs', ['lab_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_specimen_containers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lab_id')

    with op.batch_alter_table('lab_specimen_container_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lab_id')

    # ### end Alembic commands ###
