"""added price to lab test model

Revision ID: ba471631a84d
Revises: dbfbfd110da1
Create Date: 2024-09-30 05:22:08.666097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba471631a84d'
down_revision = 'dbfbfd110da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(), nullable=True))

    with op.batch_alter_table('lab_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests_version', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
