"""added package ID field

Revision ID: bb9b1175dfd6
Revises: fde865019c63
Create Date: 2025-02-06 15:59:29.227488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9b1175dfd6'
down_revision = 'fde865019c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lab_service_packages', ['package_id'], ['id'])

    with op.batch_alter_table('lab_test_records_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_records_version', schema=None) as batch_op:
        batch_op.drop_column('package_id')

    with op.batch_alter_table('lab_test_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
