"""fixed primary key issue

Revision ID: c0bc0a08bca1
Revises: 2c20bd7ea99d
Create Date: 2024-12-03 08:37:28.812875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bc0a08bca1'
down_revision = '2c20bd7ea99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_profile_assoc_version', schema=None) as batch_op:
        batch_op.drop_constraint('test_profile_assoc_version_pkey')
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_profile_assoc_version', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
        batch_op.create_primary_key('test_profile_assoc_version_pkey', ['test_id'])

    # ### end Alembic commands ###
