"""added end_datetime field

Revision ID: d3e30d892831
Revises: f0222eeeb26f
Create Date: 2024-12-02 11:18:49.481160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e30d892831'
down_revision = 'f0222eeeb26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_checkin_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_checkin_record', schema=None) as batch_op:
        batch_op.drop_column('end_datetime')

    # ### end Alembic commands ###
