"""added address, tel and pid to lab customer model

Revision ID: dbfbfd110da1
Revises: e728d05f9255
Create Date: 2024-09-29 14:14:06.287529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfbfd110da1'
down_revision = 'e728d05f9255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tel', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pid', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_customers', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('pid')
        batch_op.drop_column('tel')

    # ### end Alembic commands ###
