"""added more fields for a lab model

Revision ID: e728d05f9255
Revises: 7cbd84ad297e
Create Date: 2024-09-21 15:11:55.742616

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e728d05f9255'
down_revision = '7cbd84ad297e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
        batch_op.add_column(sa.Column('tel', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_column('tax_id')
        batch_op.drop_column('tel')
        batch_op.drop_column('email')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
