"""fixed field for discount amount

Revision ID: e7c0665d589c
Revises: 92a371dd5d43
Create Date: 2025-04-21 13:22:13.395962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c0665d589c'
down_revision = '92a371dd5d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_order_payment_records', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')

    # ### end Alembic commands ###
