"""added code field to the package model

Revision ID: e8f34298afb6
Revises: ee20c9358adc
Create Date: 2025-02-24 10:56:30.380787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f34298afb6'
down_revision = 'ee20c9358adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
