"""added SpecimenContainer and LabSpecimenContainerItem model

Revision ID: e9eca97ab125
Revises: dfa587efe305
Create Date: 2024-10-29 02:11:55.896112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9eca97ab125'
down_revision = 'dfa587efe305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_specimen_containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('container', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_specimen_container_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_test_id', sa.Integer(), nullable=True),
    sa.Column('lab_specimen_container_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lab_specimen_container_id'], ['lab_specimen_containers.id'], ),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_specimen_container_items')
    op.drop_table('lab_specimen_containers')
    # ### end Alembic commands ###
