"""added profile test order field

Revision ID: eb1039a8a5cf
Revises: 9e179cc388ab
Create Date: 2025-01-29 08:50:01.610522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1039a8a5cf'
down_revision = '9e179cc388ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_order', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.drop_column('test_order')

    # ### end Alembic commands ###
