"""added payment record model

Revision ID: ed92356d40fb
Revises: f9e9d60a7680
Create Date: 2024-10-29 05:24:59.146402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed92356d40fb'
down_revision = 'f9e9d60a7680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_order_payment_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_amount', sa.Numeric(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['lab_test_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_order_payment_records')
    # ### end Alembic commands ###
