"""added profile_price field

Revision ID: ee20c9358adc
Revises: bb9b1175dfd6
Create Date: 2025-02-13 11:09:06.904692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee20c9358adc'
down_revision = 'bb9b1175dfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
