"""added date id field to the user checkin record model

Revision ID: f0222eeeb26f
Revises: 9f3ffb19f43b
Create Date: 2024-12-02 11:16:35.419396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0222eeeb26f'
down_revision = '9f3ffb19f43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_id')

    with op.batch_alter_table('user_checkin_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_checkin_record', schema=None) as batch_op:
        batch_op.drop_column('date_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
