"""removed pkey from the assoc tables

Revision ID: f3e82fbc8e87
Revises: 1d431a6fbc4e
Create Date: 2024-11-29 08:10:37.040251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e82fbc8e87'
down_revision = '1d431a6fbc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_disease_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('customer_disease_assoc_pkey')

    with op.batch_alter_table('customer_drug_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('customer_drug_assoc_pkey')

    with op.batch_alter_table('test_profile_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('test_profile_assoc_pkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('test_profile_assoc', schema=None) as batch_op:
        batch_op.create_primary_key('test_profile_assoc_pkey', 'test_id')

    with op.batch_alter_table('customer_drug_assoc', schema=None) as batch_op:
        batch_op.create_primary_key('customer_drug_assoc_pkey')

    with op.batch_alter_table('customer_disease_assoc', schema=None) as batch_op:
        batch_op.create_primary_key('customer_disease_assoc_pkey')

    # ### end Alembic commands ###
