"""added code field to lab test

Revision ID: f98fc1567fbe
Revises: b79bdb16c8ee
Create Date: 2024-10-29 03:15:12.477705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98fc1567fbe'
down_revision = 'b79bdb16c8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))

    with op.batch_alter_table('lab_tests_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests_version', schema=None) as batch_op:
        batch_op.drop_column('code')

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
