"""added a unique constraint for two columns

Revision ID: fadaab7d39ba
Revises: fe2322afc271
Create Date: 2025-03-10 15:10:42.225846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadaab7d39ba'
down_revision = 'fe2322afc271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.create_unique_constraint('lab_service_packages_id_code_unique', ['lab_id', 'code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.drop_constraint('lab_service_packages_id_code_unique', type_='unique')

    # ### end Alembic commands ###
