"""added detail field to the lab profile model

Revision ID: fde865019c63
Revises: 99ca8abeb8cd
Create Date: 2025-02-06 10:26:19.630920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde865019c63'
down_revision = '99ca8abeb8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_test_profiles', schema=None) as batch_op:
        batch_op.drop_column('detail')

    # ### end Alembic commands ###
