"""removed unique constraint

Revision ID: fe2322afc271
Revises: be338ef6acc2
Create Date: 2025-03-10 15:05:09.409030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2322afc271'
down_revision = 'be338ef6acc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.drop_constraint('unique_lab_service_packages_code', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_service_packages', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_lab_service_packages_code', ['code'])

    # ### end Alembic commands ###
